name: CI

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: test/shell.sh

  try-machine:
    name: action on ${{ matrix.machine }}
    runs-on: ${{ matrix.machine }}
    needs: test
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        machine:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
          - windows-2019
        experimental: [false]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.
        with:
          file: test/.travis.yml

      - uses: ./.
